version: '3'
services:
  local-redis:
    image: redis:latest
    container_name: local-redis
    ports:
      - "6379:6379"

  local-redis-commander:
    image: rediscommander/redis-commander
    container_name: local-redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local-redis